# -*- coding: utf-8 -*-
"""Ambiental.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lYuE_0Br-N6R0IaPFXxCLTfl0Q75VVx2
"""

import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Dataset.csv')

df.head()

# One-hot encoding multicategorical variables
possible_incentives = [
    'Ahorro en costos',
    'Comodidad',
    'Reducción de la congestión del tráfico',
    'Beneficios medioambientales'
]

possible_desalentadores = [
    'Preocupaciones de seguridad',
    'Problemas de horarios',
    'Falta de compañeros de carpooling',
    'Inconveniencia',
    'Preferencia por la privacidad'
]

# Binary columns for each incentive
for incentive in possible_incentives:
    df[incentive] = df['incentivos'].apply(lambda x: 1 if incentive in x else 0)

# Binary columns for each desalentador
for desalentador in possible_desalentadores:
    df[desalentador] = df['desalentador'].apply(lambda x: 1 if desalentador in x else 0)

# Drop original columns
df = df.drop(columns=['incentivos', 'desalentador'])

df.tail()

# One-hot encoding single categorical variable columns
df2 = pd.get_dummies(df, columns=['edad', 'genero', 'ingreso', 'distancia', 'frecuencia', 'medio_trans', 'participado_antes', 'preocupacion_medio', 'dispuesto_carpooling', 'impacto_carpooling'])

df2

"""# Analisis

-	¿Poseer un carro privado afecta la disposición de las personas a carpooling? (Hipótesis: Si, personas con carros privados resisten al carpooling)
"""

y = df2['dispuesto_carpooling_Si']
X = df2['medio_trans_Carro propio']

# Intercept for the independent variables
X = sm.add_constant(X)

# Fit logistic regression model
model = sm.Logit(y, X)
result = model.fit()

# Regression Summary
summary = result.summary()
print(summary)

# Plotting the regression model
coeff_const = result.params['const']
coeff_carro_propio = result.params['medio_trans_Carro propio']

carro_propio_values = [0, 1]

predicted_probs = 1 / (1 + np.exp(-(coeff_const + coeff_carro_propio * np.array(carro_propio_values))))

# Bar plot
plt.bar(carro_propio_values, predicted_probs, color='royalblue')
plt.xlabel("Carro propio")
plt.ylabel("Probabilidad")
plt.title("Regresion Logistica: Disposicion a Carpooling")
plt.xticks(carro_propio_values, ['No', 'Yes'])
plt.show()

# Assuming your dataframe is called df
# Define the dependent variable (willingness to carpool) and independent variables (income categories)
X = df2[['ingreso_$1000 - $2000', 'ingreso_$2000 - $5000', 'ingreso_< $1000']]
y = df2['dispuesto_carpooling_Si']

# Add a constant to the independent variables (intercept)
X = sm.add_constant(X)

# Fit the logistic regression model
model = sm.Logit(y, X)
result = model.fit()

# Print the summary of the regression results
print(result.summary())

# Extract the coefficients for the income categories
coef_income_1000_2000 = result.params['ingreso_$1000 - $2000']
coef_income_2000_5000 = result.params['ingreso_$2000 - $5000']
coef_income_less_1000 = result.params['ingreso_< $1000']

# Create a range of income values (you can adjust this as needed)
income_values = np.linspace(-1, 2, 100)

# Calculate the predicted probabilities for each income value
predicted_probs_1000_2000 = 1 / (1 + np.exp(-(result.params['const'] + coef_income_1000_2000 * income_values)))
predicted_probs_2000_5000 = 1 / (1 + np.exp(-(result.params['const'] + coef_income_2000_5000 * income_values)))
predicted_probs_less_1000 = 1 / (1 + np.exp(-(result.params['const'] + coef_income_less_1000 * income_values)))

# Plot the predicted probabilities
plt.figure(figsize=(8, 6))
plt.plot(income_values, predicted_probs_1000_2000, label='$1000 - $2000')
plt.plot(income_values, predicted_probs_2000_5000, label='$2000 - $5000')
plt.plot(income_values, predicted_probs_less_1000, label='< $1000')
plt.xlabel("Income Category")
plt.ylabel("Probability of Willingness to Carpool")
plt.title("Logistic Regression: Probability vs. Income Category")
plt.legend()
plt.grid()
plt.show()